version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    ports:
      - 8001:8001  # Expose the port that Gunicorn is listening on

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"  
